name: Build Android

on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        description: "Channel"
        required: true
        default: "development"
        options:
          - "development"
          - "preview"
          - "production"
      build_logger_level:
        type: choice
        description: "Build Logger Level"
        required: true
        default: "warn"
        options:
          - "trace"
          - "debug"
          - "info"
          - "warn"
          - "error"
          - "fatal"
          - "silent"

jobs:
  build-android:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'go-west-tech-jsc/golfy' && github.event_name != 'pull_request' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.CHECKOUT_REPOSITORY }}
          ref: ${{ github.event.inputs.channel == 'development' && 'develop' || github.event.inputs.channel == 'preview' && 'staging' || github.event.inputs.channel == 'production' && 'main' }}
          ssh-key: ${{ secrets.CHECKOUT_SSH_KEY }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Setup EAS
        run: pnpm add -g eas-cli

      - name: Install dependencies
        run: pnpm install

      - name: Build Android
        run: EXPO_TOKEN=${{ secrets.EXPO_TOKEN }} eas build --platform=android --profile=${{ github.event.inputs.channel }} --build-logger-level=${{ github.event.inputs.build_logger_level }} --local --output=app-release.aab --non-interactive
        working-directory: apps/expo
