name: Build iOS

on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        description: 'Channel'
        required: true
        default: 'development'
        options:
          - 'development'
          - 'preview'
          - 'production'

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.CHECKOUT_REPOSITORY }}
          ref: ${{ github.event.inputs.channel == 'development' && 'develop' || github.event.inputs.channel == 'preview' && 'staging' || github.event.inputs.channel == 'production' && 'main' }}
          ssh-key: ${{ secrets.CHECKOUT_SSH_KEY }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
  
      - name: Install Expo CLI
        run: pnpm add -g expo-cli eas-cli