name: Build Server

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: "Branch"
        required: true
        default: "develop"
        options:
          - "develop"
          - "staging"
          - "main"

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: go-west-tech-jsc/frappe-docker
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          file: images/production/Containerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.branch }}
          # build-args: |
          #   CONTAINERD_VERSION=1.5.5

      - name: Clean up
        run: docker buildx rm