name: Build iOS

on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        description: 'Channel'
        required: true
        default: 'development'
        options:
          - 'development'
          - 'preview'
          - 'production'

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.CHECKOUT_REPOSITORY }}
          ref: ${{ github.event.inputs.channel == 'development' && 'develop' || github.event.inputs.channel == 'preview' && 'staging' || github.event.inputs.channel == 'production' && 'main' }}
          ssh-key: ${{ secrets.CHECKOUT_SSH_KEY }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
  
      - name: Install CLI
        run: pnpm add -g eas-cli
      
      - name: Install dependencies
        run: pnpm install

      - name: Build Golfy Alpha
        run: EXPO_TOKEN=${{ secrets.EXPO_TOKEN }} pnpm ios:eas-local:development-store
        working-directory: apps/expo
        if: github.event.inputs.channel == 'development'
      
      - name: Build Golfy Beta
        run: EXPO_TOKEN=${{ secrets.EXPO_TOKEN }} pnpm ios:eas-local:preview
        working-directory: apps/expo
        if: github.event.inputs.channel == 'preview'
      
      - name: Build Golfy
        run: EXPO_TOKEN=${{ secrets.EXPO_TOKEN }} pnpm ios:eas-local:production
        working-directory: apps/expo
        if: github.event.inputs.channel == 'production'

