name: Build iOS

on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        description: "Channel"
        required: true
        default: "development"
        options:
          - "development"
          - "preview"
          - "production"

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: ./.github/actions/setup-expo-builder/action.yaml
        with:
          channel: ${{ github.event.inputs.channel }}

      - name: Build iOS
        run: EXPO_TOKEN=${{ secrets.EXPO_TOKEN }} eas build --platform=ios --profile=${{ github.event.inputs.channel }} --build-logger-level=warn --local --output=App.ipa --non-interactive
        working-directory: apps/expo

      - name: Upload app to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: apps/expo/App.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
