name: Build iOS

on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        description: "Channel"
        required: true
        default: "development"
        options:
          - "development"
          - "preview"
          - "production"

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.CHECKOUT_REPOSITORY }}
          ref: ${{ github.event.inputs.channel == 'development' && 'develop' || github.event.inputs.channel == 'preview' && 'staging' || github.event.inputs.channel == 'production' && 'main' }}
          ssh-key: ${{ secrets.CHECKOUT_SSH_KEY }}
  
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
  
      - name: Install CLI
        shell: bash
        run: pnpm add -g eas-cli
      
      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Build iOS
        run: EXPO_TOKEN=${{ secrets.EXPO_TOKEN }} eas build --platform=ios --profile=${{ github.event.inputs.channel }} --build-logger-level=warn --local --output=App.ipa --non-interactive
        working-directory: apps/expo

      - name: Upload app to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: apps/expo/App.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
