name: Clean Up Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete completed workflow runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
            --paginate --jq '.workflow_runs[] | select(.status == "completed") | .id' | \
          xargs -I {} gh api repos/${{ github.repository }}/actions/runs/{} -X DELETE
